# Generated by Django 3.0.2 on 2020-01-16 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('url', models.CharField(max_length=255)),
                ('nb_products', models.IntegerField(verbose_name='Nombre de produits de la catégorie')),
            ],
            options={
                'verbose_name': 'catégorie',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('email', models.CharField(max_length=255, verbose_name='Nom')),
                ('password', models.CharField(max_length=255, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('url', models.CharField(max_length=255)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='foodSearch.Category')),
            ],
            options={
                'verbose_name': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodSearch.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodSearch.User')),
            ],
            options={
                'verbose_name': 'favoris',
            },
        ),
    ]
