# Generated by Django 3.0.2 on 2020-02-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0002_favorite_initial_search_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formated_brands',
            field=models.CharField(default='', max_length=200, verbose_name='Marque'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='formated_name',
            field=models.CharField(default='', max_length=200, verbose_name='Nom'),
            preserve_default=False,
        ),
    ]
