# Generated by Django 3.0.2 on 2020-01-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0002_auto_20200116_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='link_picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
