# Generated by Django 3.0.2 on 2020-01-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0003_auto_20200118_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='link_picture',
            new_name='image_small_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
