# Generated by Django 3.0.2 on 2020-01-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0006_auto_20200119_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sodium_100g',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_100g',
            field=models.FloatField(null=True),
        ),
    ]
