# Generated by Django 3.0.2 on 2020-02-26 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0006_auto_20200211_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='substitute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute', to='foodSearch.Product'),
        ),
    ]
