# Generated by Django 3.0.2 on 2020-01-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0007_auto_20200122_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salt_100g',
            field=models.FloatField(null=True),
        ),
    ]
