# Generated by Django 3.0.2 on 2020-01-28 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('brands', models.CharField(max_length=200, verbose_name='Marque')),
                ('url', models.URLField(null=True)),
                ('image_url', models.URLField(null=True)),
                ('image_small_url', models.URLField(null=True)),
                ('nutrition_grade_fr', models.CharField(max_length=1)),
                ('saturated_fat_100g', models.FloatField(null=True)),
                ('carbohydrates_100g', models.FloatField(null=True)),
                ('energy_100g', models.FloatField(null=True)),
                ('sugars_100g', models.FloatField(null=True)),
                ('sodium_100g', models.FloatField(null=True)),
                ('salt_100g', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'envoi")),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='foodSearch.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('products', models.ManyToManyField(blank=True, related_name='categories', to='foodSearch.Product')),
            ],
        ),
    ]
