# Generated by Django 3.0.2 on 2020-02-10 10:45

from django.db import migrations, models
import foodSearch.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='initial_search_product',
            field=models.IntegerField(null=True, verbose_name=foodSearch.models.Product),
        ),
    ]
