# Generated by Django 3.0.2 on 2020-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodSearch', '0008_auto_20200226_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='formated_brands',
            new_name='formatted_brands',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='formated_name',
            new_name='formatted_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small_url',
            field=models.URLField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(default='DEFAULT VALUE'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(default='DEFAULT VALUE'),
        ),
    ]
